"use client";

import { useEffect, useMemo, useRef, useState } from "react";

// Generated by scripts/generate-emoji-data.mjs (Emojibase, German).
interface EmojiGroup {
  key: string;
  label: string;
  icon: string;
  /** [emoji, lower-case German label + search terms] */
  emojis: [string, string][];
}

// ~40 KB gzipped: loaded on first open only, then kept for the session.
let groupsPromise: Promise<EmojiGroup[]> | null = null;
function loadGroups() {
  groupsPromise ??= import("@/lib/emoji/emoji-data.json").then((m) => m.default.groups as EmojiGroup[]);
  return groupsPromise;
}

const RECENTS_KEY = "pigeon-emoji-recents";
const MAX_RECENTS = 32;
const RECENTS_GROUP_KEY = "recents";

function readRecents(): string[] {
  try {
    const raw = window.localStorage.getItem(RECENTS_KEY);
    const parsed: unknown = raw ? JSON.parse(raw) : [];
    return Array.isArray(parsed) ? parsed.filter((e): e is string => typeof e === "string") : [];
  } catch {
    return [];
  }
}

function saveRecents(recents: string[]) {
  try {
    window.localStorage.setItem(RECENTS_KEY, JSON.stringify(recents));
  } catch {}
}

interface EmojiPickerProps {
  onSelect: (emoji: string) => void;
  /** ⌫ — the phone keyboard is hidden while the panel is open. */
  onBackspace: () => void;
}

/**
 * The emoji panel under the composer, like WhatsApp's: search (German),
 * category tabs, "Zuletzt verwendet". Native emoji glyphs, so they look
 * exactly like the ones the keyboard would insert.
 */
export function EmojiPicker({ onSelect, onBackspace }: EmojiPickerProps) {
  const [groups, setGroups] = useState<EmojiGroup[] | null>(null);
  const [recents, setRecents] = useState<string[]>([]);
  const [query, setQuery] = useState("");
  const [activeKey, setActiveKey] = useState<string | null>(null);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let cancelled = false;
    void loadGroups().then((loaded) => {
      if (!cancelled) setGroups(loaded);
    });
    setRecents(readRecents());
    return () => {
      cancelled = true;
    };
  }, []);

  const sections = useMemo(() => {
    if (!groups) return [];
    const recentGroup: EmojiGroup = {
      key: RECENTS_GROUP_KEY,
      label: "Zuletzt verwendet",
      icon: "🕘",
      emojis: recents.map((e) => [e, ""]),
    };
    return recents.length > 0 ? [recentGroup, ...groups] : groups;
  }, [groups, recents]);

  const searchResults = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q || !groups) return null;
    const words = q.split(/\s+/);
    return groups.flatMap((g) => g.emojis).filter(([, text]) => words.every((w) => text.includes(w)));
  }, [groups, query]);

  function pick(emoji: string) {
    onSelect(emoji);
    const next = [emoji, ...recents.filter((e) => e !== emoji)].slice(0, MAX_RECENTS);
    saveRecents(next);
    // Not re-sorting the recents tab under the finger while it's open —
    // the new order shows the next time the panel opens.
    if (!recents.includes(emoji)) setRecents(next);
  }

  function jumpTo(key: string) {
    setQuery("");
    setActiveKey(key);
    requestAnimationFrame(() => {
      scrollRef.current?.querySelector(`[data-group="${key}"]`)?.scrollIntoView({ block: "start" });
    });
  }

  // Highlights the tab of the section currently at the top.
  function handleScroll() {
    const el = scrollRef.current;
    if (!el) return;
    let current: string | null = null;
    for (const section of Array.from(el.querySelectorAll<HTMLElement>("[data-group]"))) {
      // offsetTop is relative to the scroll container (it's `relative`).
      if (section.offsetTop <= el.scrollTop + 8) current = section.dataset.group ?? null;
    }
    setActiveKey(current);
  }

  const renderGrid = (emojis: [string, string][], keyPrefix: string) => (
    <div className="grid grid-cols-8 sm:grid-cols-10">
      {emojis.map(([emoji]) => (
        <button
          key={`${keyPrefix}-${emoji}`}
          type="button"
          // Keeps focus (and, on desktop, the cursor) in the text field.
          onMouseDown={(event) => event.preventDefault()}
          onClick={() => pick(emoji)}
          className="flex aspect-square items-center justify-center rounded-lg text-2xl leading-none hover:bg-neutral-100 active:scale-90 dark:hover:bg-night-raised"
        >
          {emoji}
        </button>
      ))}
    </div>
  );

  return (
    <div className="animate-fade-in mt-2 flex h-72 flex-col overflow-hidden rounded-2xl border border-neutral-200 bg-white dark:border-night-border dark:bg-night-surface">
      <div className="flex items-center gap-2 border-b border-neutral-100 p-2 dark:border-night-border">
        <input
          type="search"
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          placeholder="Emoji suchen…"
          aria-label="Emoji suchen"
          className="min-w-0 flex-1 rounded-full bg-neutral-100 px-3 py-1.5 text-base sm:text-sm dark:bg-night-raised"
        />
        <button
          type="button"
          onMouseDown={(event) => event.preventDefault()}
          onClick={onBackspace}
          aria-label="Zeichen löschen"
          title="Löschen"
          className="flex-shrink-0 rounded-full p-2 text-neutral-500 hover:bg-neutral-100 dark:text-night-muted dark:hover:bg-night-raised"
        >
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="h-5 w-5">
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 9.75 14.25 12m0 0 2.25 2.25M14.25 12l2.25-2.25M14.25 12 12 14.25m-2.58 4.92-6.37-6.38a1.125 1.125 0 0 1 0-1.59L9.42 4.83c.21-.21.5-.33.8-.33H19.5a2.25 2.25 0 0 1 2.25 2.25v10.5a2.25 2.25 0 0 1-2.25 2.25h-9.28c-.3 0-.59-.12-.8-.33Z" />
          </svg>
        </button>
      </div>

      <div ref={scrollRef} onScroll={handleScroll} className="relative min-h-0 flex-1 overflow-y-auto overscroll-contain px-2 pb-2">
        {!groups ? (
          <p className="py-8 text-center text-sm text-neutral-400 dark:text-night-muted">Emojis werden geladen…</p>
        ) : searchResults ? (
          searchResults.length > 0 ? (
            <div className="pt-2">{renderGrid(searchResults, "search")}</div>
          ) : (
            <p className="py-8 text-center text-sm text-neutral-400 dark:text-night-muted">Kein Emoji gefunden.</p>
          )
        ) : (
          sections.map((group) => (
            <section key={group.key} data-group={group.key} className="[content-visibility:auto]">
              <h3 className="sticky top-0 z-10 bg-white/95 px-1 py-1.5 text-[11px] font-semibold uppercase tracking-wide text-neutral-400 backdrop-blur dark:bg-night-surface/95 dark:text-night-muted">
                {group.label}
              </h3>
              {renderGrid(group.emojis, group.key)}
            </section>
          ))
        )}
      </div>

      {groups && (
        <nav className="flex justify-between gap-1 border-t border-neutral-100 px-1 py-1 dark:border-night-border" aria-label="Emoji-Kategorien">
          {sections.map((group) => (
            <button
              key={group.key}
              type="button"
              onMouseDown={(event) => event.preventDefault()}
              onClick={() => jumpTo(group.key)}
              aria-label={group.label}
              title={group.label}
              className={`flex-1 rounded-lg py-1 text-lg leading-none transition-opacity ${
                (activeKey ?? sections[0]?.key) === group.key && !searchResults
                  ? "bg-neutral-100 opacity-100 dark:bg-night-raised"
                  : "opacity-50 hover:opacity-100"
              }`}
            >
              {group.icon}
            </button>
          ))}
        </nav>
      )}
    </div>
  );
}
