// The app's chimes (public/sounds/, generated by scripts/generate-sounds.py).
// Each one can be switched off in the settings (lib/sound-settings.ts).
//
// iOS Safari only lets an <audio> element play if play() was first called
// synchronously inside a user gesture — a play() from a useEffect or
// setTimeout later is silently rejected. So playEncryptStart() must be
// called directly from the send handler, and it also "unlocks" the end
// chime there (muted play + pause), which then plays for real ~5s later.

import { isSoundEnabled } from "@/lib/sound-settings";

const START_SOUND_SRC = "/sounds/encrypt-start.mp3";
const END_SOUND_SRC = "/sounds/encrypt-end.mp3";
const VOLUME = 0.5;

let startAudio: HTMLAudioElement | null = null;
let endAudio: HTMLAudioElement | null = null;

function getAudio(which: "start" | "end"): HTMLAudioElement | null {
  if (typeof Audio === "undefined") return null;
  if (which === "start") {
    startAudio ??= Object.assign(new Audio(START_SOUND_SRC), { volume: VOLUME, preload: "auto" });
    return startAudio;
  }
  endAudio ??= Object.assign(new Audio(END_SOUND_SRC), { volume: VOLUME, preload: "auto" });
  return endAudio;
}

function play(audio: HTMLAudioElement | null) {
  if (!audio) return;
  audio.muted = false;
  audio.currentTime = 0;
  audio.play().catch(() => {});
}

/** Warm the cache so the first send doesn't wait on the network. */
export function preloadChimeSounds() {
  getAudio("start")?.load();
  getAudio("end")?.load();
}

/** Call synchronously from the user's send gesture (click/submit). */
export function playEncryptStart() {
  if (isSoundEnabled("send")) play(getAudio("start"));

  // Only worth unlocking if the end chime is going to play later.
  if (!isSoundEnabled("encrypted")) return;
  const end = getAudio("end");
  if (end && end.paused) {
    end.muted = true;
    end
      .play()
      .then(() => {
        end.pause();
        end.currentTime = 0;
        end.muted = false;
      })
      .catch(() => {
        end.muted = false;
      });
  }
}

/** End of a chat message's hacker show. */
export function playEncryptEnd() {
  if (isSoundEnabled("encrypted")) play(getAudio("end"));
}

/** A pigeon letter was just sent — call from the send gesture. */
export function playPigeonTakeoff() {
  if (isSoundEnabled("takeoff")) play(getAudio("end"));
}

/** Settings preview: plays regardless of the switches (it's a gesture). */
export function previewSound(which: "send" | "encrypted" | "takeoff") {
  play(getAudio(which === "send" ? "start" : "end"));
}
