// The two <EncryptionSequence /> chimes (public/sounds/, generated by
// scripts/generate-sounds.py).
//
// iOS Safari only lets an <audio> element play if play() was first called
// synchronously inside a user gesture — a play() from a useEffect or
// setTimeout later is silently rejected. So playEncryptStart() must be
// called directly from the send handler, and it also "unlocks" the end
// chime there (muted play + pause), which then plays for real ~5s later.

const START_SOUND_SRC = "/sounds/encrypt-start.mp3";
const END_SOUND_SRC = "/sounds/encrypt-end.mp3";
const VOLUME = 0.5;

let startAudio: HTMLAudioElement | null = null;
let endAudio: HTMLAudioElement | null = null;

function getAudio(which: "start" | "end"): HTMLAudioElement | null {
  if (typeof Audio === "undefined") return null;
  if (which === "start") {
    startAudio ??= Object.assign(new Audio(START_SOUND_SRC), { volume: VOLUME, preload: "auto" });
    return startAudio;
  }
  endAudio ??= Object.assign(new Audio(END_SOUND_SRC), { volume: VOLUME, preload: "auto" });
  return endAudio;
}

/** Warm the cache so the first send doesn't wait on the network. */
export function preloadChimeSounds() {
  getAudio("start")?.load();
  getAudio("end")?.load();
}

/** Call synchronously from the user's send gesture (click/submit). */
export function playEncryptStart() {
  const start = getAudio("start");
  if (start) {
    start.currentTime = 0;
    start.play().catch(() => {});
  }

  const end = getAudio("end");
  if (end && end.paused) {
    end.muted = true;
    end
      .play()
      .then(() => {
        end.pause();
        end.currentTime = 0;
        end.muted = false;
      })
      .catch(() => {
        end.muted = false;
      });
  }
}

export function playEncryptEnd() {
  const end = getAudio("end");
  if (!end) return;
  end.muted = false;
  end.currentTime = 0;
  end.play().catch(() => {});
}
